spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authcore_db
    username: root
    password: F@H12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ✅ Use 'validate' in production, 'update' only for development
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false
    locations: classpath:db/migration

  profiles:
    active: default

server:
  port: 8080
  error:
    include-stacktrace: on_param
